---
title: "Projects"
---

# **Project 1: Analysis of Predective Models with the Physicochemical Properties of Wine Versus Wine Quality**

Develop several predictive models and determine which of the models predicts wine quality the best​.

-   Wine industry generated over \$200 billion annually within the United States in 2017​

-   Dataset: sourced from the IC Irvine Machine Learning Repository​

-   Contains detailed information on the chemical composition of red and white wines​

# **Project 2: Random forest is an ensemble-based method that uses multiple decision trees constructed via bagging (bootstrapped aggregating) with random feature selection. Due to random selection of a subset of all features in tree-growing, it can handle large, noisy, or even missing data. We will use randomForest package in this assignment.**

## **DATA: OFP - Visits to Physician Office Data**

Predictors

-   **ofp**: number of physician office visits

-   **ofnpv**: number of nonphysician office visits

-   **opp**: number of physician outpatient visits

-   **opnp**: number of nonphysician outpatient visits

-   **emr**: number of emergency room visits

-   **hosp** number of hospitalizations

-   **numchron**: number of chronic conditions

-   **adldiff**: the person has a condition that limits activities of daily living?

-   **age**: age in years (divided by 10)

-   **black**: is the person African or American?

-   **sex**: is the person male ?

-   **married**: is the person married ?

-   **school**: number of years of education

-   **faminc**: family income in \$10000

-   **employed**: is the person employed ?

-   **privins**: is the person covered by private health insurance ?

-   **medicaid**: is the person covered by medicaid ?

-   **region**: the region (noreast, midwest,west)

**Target Variable**

-   **hlth**: self-perceived health (excellent, poor, other)

There are 4406 observations and 18 predictors in the data set to predict our outcome variable hlth

**adldiff, black, sex, maried, employed, privins, medicaid, region, hlth**

-   Split **OFP_data** into training and testing sets, keep 30% of the data for validation. Use the **set.seed(5410)** seed values and name the training and test sets as **OFP_train** and **OFP_test**, respectively.
